require("antonstrand.core.options")
require("antonstrand.core.keymaps")
require("antonstrand.core.fsharp")
require("antonstrand.core.highlight_yank")
require("antonstrand.core.switch_case")
require("antonstrand.core.dictionary")
